version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Zurich"
    open-pull-requests-limit: 3
    versioning-strategy: "increase-if-necessary"
    commit-message:
      prefix: "deps"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Zurich"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "ci"
