CATALOG = {
    "M31": {
         "ra": 10.6847,
         "dec": 41.2692,
         "name": "Galaxie d’Andromède",
         "type": "galaxy",
         "size_arcmin": 140,
         "magnitude": 3.4,
         "difficulty": 1,
    },
    "M42": {
	"ra": 83.8221,
        "dec": -5.3911,
        "name": "Nébuleuse d’Orion",
        "type": "nebula",
        "size_arcmin": 85,
        "magnitude": 4.0,
        "difficulty": 1,
    },
    "M51": {
	"ra": 202.4842,
        "dec": 47.2306,
        "size_arcmin": 11,
        "name": "Galaxie du Tourbillon",
        "type": "galaxy",
        "magnitude": 8.4,
        "difficulty": 3,
    },
    "M81": {
	"ra": 148.8882,
        "dec": 69.0653,
        "size_arcmin": 27,
        "name": "Galaxie de Bode",
        "type": "galaxy",
        "magnitude": 6.9,
        "difficulty": 2,
    },
    "M101": {
	"ra": 210.8023,
        "dec": 54.3489,
        "size_arcmin": 28,
        "name": "Galaxie du Moulinet",
        "type": "galaxy",
        "magnitude": 7.9,
        "difficulty": 3,
    },
    "Rosette": {
	"ra": 97.5,
        "dec": 4.95,
        "size_arcmin": 80,
        "name": "Nébuleuse de la Rosette",
        "type": "nebula",
        "magnitude": 9.0,
        "difficulty": 2,
    },
    "NorthAmerica": {
	"ra": 314.75,
        "dec": 44.33,
        "size_arcmin": 120,
        "name": "Nébuleuse North America",
        "type": "nebula",
        "magnitude": 4.0,
        "difficulty": 2,
    },
    "M45": {
        "ra": 56.750,
        "dec": 24.117,
        "name": "Pléiades",
        "type": "cluster",
        "size_arcmin": 110,
        "magnitude": 1.6,
        "difficulty": 1,
    },
    "M13": {
        "ra": 250.423,
        "dec": 36.461,
        "size_arcmin": 20,
        "name": "Grand amas d’Hercule",
        "type": "cluster",
        "magnitude": 5.8,
        "difficulty": 1,
    },
    "M27": {
        "ra": 299.900,
        "dec": 22.717,
        "name": "Nébuleuse Dumbbell",
        "type": "planetary_nebula",
        "size_arcmin": 8,
        "magnitude": 7.5,
        "difficulty": 2,
    },
    
    "M33": {
        "ra": 23.4621,
        "dec": 30.6599,
        "name": "Galaxie du Triangle",
        "type": "galaxy",
        "size_arcmin": 70,
        "magnitude": 5.7,
        "difficulty": 2,
    },

    "M57": {
        "ra": 283.396,
        "dec": 33.029,
        "size_arcmin": 1.4,
        "name": "Nébuleuse de l'Anneau",
        "type": "planetary_nebula",
        "magnitude": 8.8,
        "difficulty": 3,
    },

    "M16": {
        "ra": 274.700,
        "dec": -13.806,
        "name": "Aigle",
        "type": "nebula",
        "size_arcmin": 35,
        "magnitude": 6.4,
        "difficulty": 2,
    },

    "M17": {
        "name": "Omega",
        "type": "nebula",
        "ra": 275.100,
        "dec": -16.171,
        "size_arcmin": 46,
        "magnitude": 6.0,
        "difficulty": 2,
    },

    "IC1396": {
        "name": "Trompe d'Éléphant",
        "type": "nebula",
        "ra": 324.750,
        "dec": 57.500,
        "size_arcmin": 170,
        "magnitude": 7.0,
        "difficulty": 3,
    },

    "IC1805": {
         "ra": 38.500,
        "dec": 61.400,
        "name": "Heart Nebula",
        "type": "nebula",
        "size_arcmin": 150,
        "magnitude": 6.5,
        "difficulty": 2,
    },

    "IC1848": {
        "ra": 39.750,
        "dec": 60.400,
        "name": "Soul Nebula",
        "type": "nebula",
        "size_arcmin": 150,
        "magnitude": 6.5,
        "difficulty": 2,
    },

    "Heart": {
        "ra": 2.55,
        "dec": 61.43,
        "size_arcmin": 120,
        "name": "Heart Nebula",
        "type": "nebula",
        "magnitude": 6.5,
        "difficulty": 3,
    },
    "Soul": {
        "ra": 2.85,
        "dec": 60.43,
        "size_arcmin": 150,
        "name": "Soul Nebula",
        "type": "nebula",
        "magnitude": 6.5,
        "difficulty": 3,
    },
    "Veil": {
        "ra": 20.75,
        "dec": 30.7,
        "size_arcmin": 180,
        "name": "Veil Nebula",
        "type": "nebula",
        "magnitude": 7.0,
        "difficulty": 3,
    },



    
    }
