CATALOG = {
    "M31": {
        "name": "Galaxie d’Andromède",
        "type": "galaxy",
        "size_arcmin": 140,
        "magnitude": 3.4,
        "difficulty": 1,
    },
    "M42": {
        "name": "Nébuleuse d’Orion",
        "type": "nebula",
        "size_arcmin": 85,
        "magnitude": 4.0,
        "difficulty": 1,
    },
    "M51": {
        "name": "Galaxie du Tourbillon",
        "type": "galaxy",
        "size_arcmin": 11,
        "magnitude": 8.4,
        "difficulty": 3,
    },
    "M81": {
        "name": "Galaxie de Bode",
        "type": "galaxy",
        "size_arcmin": 27,
        "magnitude": 6.9,
        "difficulty": 2,
    },
    "M101": {
        "name": "Galaxie du Moulinet",
        "type": "galaxy",
        "size_arcmin": 28,
        "magnitude": 7.9,
        "difficulty": 3,
    },
    "Rosette": {
        "name": "Nébuleuse de la Rosette",
        "type": "nebula",
        "size_arcmin": 80,
        "magnitude": 9.0,
        "difficulty": 2,
    },
    "NorthAmerica": {
        "name": "Nébuleuse North America",
        "type": "nebula",
        "size_arcmin": 120,
        "magnitude": 4.0,
        "difficulty": 2,
    },
    "M45": {
        "name": "Pléiades",
        "type": "cluster",
        "size_arcmin": 110,
        "magnitude": 1.6,
        "difficulty": 1,
    },
    "M13": {
        "name": "Grand amas d’Hercule",
        "type": "cluster",
        "size_arcmin": 20,
        "magnitude": 5.8,
        "difficulty": 1,
    },
    "M27": {
        "name": "Nébuleuse Dumbbell",
        "type": "planetary_nebula",
        "size_arcmin": 8,
        "magnitude": 7.5,
        "difficulty": 2,
    },
}
