CATALOG = {
    "M31": {
         "ra": 10.6847,
         "dec": 41.2692,
         "name": "Galaxie d’Andromède",
         "type": "galaxy",
         "size_arcmin": 140,
         "magnitude": 3.4,
         "difficulty": 1,
    },
    "M42": {
	"ra": 83.8221,
        "dec": -5.3911,
        "name": "Nébuleuse d’Orion",
        "type": "nebula",
        "size_arcmin": 85,
        "magnitude": 4.0,
        "difficulty": 1,
    },
    "M51": {
	"ra": 202.4842,
        "dec": 47.2306,
        "size_arcmin": 11,
        "name": "Galaxie du Tourbillon",
        "type": "galaxy",
        "size_arcmin": 11,
        "magnitude": 8.4,
        "difficulty": 3,
    },
    "M81": {
	"ra": 148.8882,
        "dec": 69.0653,
        "size_arcmin": 27,
        "name": "Galaxie de Bode",
        "type": "galaxy",
        "size_arcmin": 27,
        "magnitude": 6.9,
        "difficulty": 2,
    },
    "M101": {
	"ra": 210.8023,
        "dec": 54.3489,
        "size_arcmin": 28,
        "name": "Galaxie du Moulinet",
        "type": "galaxy",
        "size_arcmin": 28,
        "magnitude": 7.9,
        "difficulty": 3,
    },
    "Rosette": {
	"ra": 97.5,
        "dec": 4.95,
        "size_arcmin": 80,
        "name": "Nébuleuse de la Rosette",
        "type": "nebula",
        "size_arcmin": 80,
        "magnitude": 9.0,
        "difficulty": 2,
    },
    "NorthAmerica": {
	"ra": 314.75,
        "dec": 44.33,
        "size_arcmin": 120,
        "name": "Nébuleuse North America",
        "type": "nebula",
        "size_arcmin": 120,
        "magnitude": 4.0,
        "difficulty": 2,
    },
    "M45": {
        "name": "Pléiades",
        "type": "cluster",
        "size_arcmin": 110,
        "magnitude": 1.6,
        "difficulty": 1,
    },
    "M13": {
        "name": "Grand amas d’Hercule",
        "type": "cluster",
        "size_arcmin": 20,
        "magnitude": 5.8,
        "difficulty": 1,
    },
    "M27": {
        "name": "Nébuleuse Dumbbell",
        "type": "planetary_nebula",
        "size_arcmin": 8,
        "magnitude": 7.5,
        "difficulty": 2,
    },
}
